### PR TITLE
Do not run requestTransform again after retry

### LINKED ISSUE #48: Reset transformRequest to avoid double encoding
Right now the retry uses the same config as the first request. So the `transformRequest` happens twice.

So for the retried request should reset it to be `[]`.

Alternatively axios should just not modify the config input here: https://github.com/axios/axios/blob/2b8562694ec4322392cb0cf0d27fe69bd290fcb2/lib/core/dispatchRequest.js#L25

### PR DESCRIPTION
**Pull request by finnp**
fixes #48

### CODE REVIEW

**Comment by yns01** [comment]
Thank you for your contribution!

LGTM. @jlopezxs ?

**Comment by finnp** [comment]
I updated the pull request to get git the conflict :)

**Comment by jlopezxs** [comment]
Do you have a use case on this is a "big problem"?

**Comment by finnp** [comment]
It's actually not that important. We had JSON encoding in the transform, so the data was double encoded. 

So we changed the transform to check if the body is an object first. Probably that's just generally how people should use axios.

**Pull request merged**
