### PR TITLE
Fixed TS definitions.

### PR DESCRIPTION
**Pull request by c1moore**

### CODE REVIEW

**Comment by c1moore** [comment]
@moose56 @rubennorte Can this be merged in?

**Comment by mawrkus** [comment]
@sviridoff may I ask you to have a look at this, my knowledge of TypeScript is limited. Thanks!

**Comment by c1moore** [comment]
@mawrkus @sviridoff Would it be possible to get this reviewed and merged in soon?

**Comment by mawrkus** [comment]
Thanks!

**Pull request merged**
