### PR TITLE
Upgrade to newest axios version

### LINKED ISSUE #159: Argument of type 'AxiosInstance' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'
When I try to configure axiosRetry using an axios client as specified in the usage section of the [README](https://github.com/softonic/axios-retry#usage)

```ts
// Works with custom axios instances
const client = axios.create({ baseURL: 'http://example.com' });
axiosRetry(client, { retries: 3 });
```

I get the following error:
> Argument of type 'AxiosInstance' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'

Setup Info:
Platform: `macOS Mojave v10.14.6`
Typescript: `v4.1.2`
Node.js: `v12.18.3`

### PR DESCRIPTION
**Pull request by Agreon**
closes #159

### CODE REVIEW

**Comment by mindhells** [comment]
could you please explain the purpose of this PR?
I don't understand how changing a dev dependency here solves the issue reported in #159
Why changing toBe for toEqual for primitive values?

**Comment by Tohaker** [comment]
The new version of axios contains updated types that are incompatible with the current version of this package - if anyone wants to use a recent version of axios, they can't use this package. Merging this PR will solve the linked issue no question. 

The tests changing is another story, probably one for another PR/discussion

**Comment by mindhells** [comment]
@Tohaker 

> The new version of axios contains updated types that are incompatible with the current version of this package - if anyone wants to use a recent version of axios, they can't use this package. Merging this PR will solve the linked issue no question.
> 
> The tests changing is another story, probably one for another PR/discussion

Are you actually able to reproduce the problem described in #159, because I'm not. 
If I create a basic TS sample with the latest versions of each library it just works, no problem with the types.
- "axios": "0.27.2",
- "axios-retry": "3.2.5"

Maybe I'm missing something, can you @Tohaker point exactly where is the problem with the types that makes this PR necessary?

**Comment by Tohaker** [comment]
I'm not too sure why it works on a new project - upgrading the package versions from a simple wrapper around an axios client generates the exact same error as the issue states; It claims the types are incompatible (yet have the same names)

I'll look closer at it tomorrow, perhaps I spoke a little too soon 😆

**Comment by Tohaker** [comment]
Ok my bad - it was a monorepo resolution error

**Comment by mindhells** [comment]
closing for inactivity but thanks anyway

**Comment by amalmohann-dgnl** [comment]
@Tohaker how did you resolved the monorepo?

**Comment by Tohaker** [comment]
Sorry, this was 2.5 years ago so I can't remember at all what I did (probably a lesson to me to explain better in the future!) 
My best guess is that deleting `node_modules` and `package-lock.json` and reinstalling would help if you're still facing it

**Pull request closed without merging**
