### PR TITLE
Add the retryOnTimeout option

### PR DESCRIPTION
**Pull request by ValentinH**
As requested in  #39

### CODE REVIEW

**Comment by yns01** [comment]
@jlopezxs Did you have a chance to look at this PR? It's related to issue https://github.com/softonic/axios-retry/issues/39

**Comment by jlopezxs** [comment]
This is nice but I think you can do that with retryCondition. I don't know if is good idea start creating Boolean parameters only to apply a "custom retry logic".

**Comment by ValentinH** [comment]
I understand that we can override the  `retryCondition` with custom logic. However, I ended up copying the `isRetryableError`, `isIdempotentRequestError` and `isNetworkOrIdempotentRequestError` in my code just for removing the checks about `error.code !== 'ECONNABORTED'`. This doesn't feel right.

I also understand that the solution I propose isn't the best one but I couldn't find another way so far... :/

**Comment by ValentinH** [comment]
Any chance we could reconsider this PR?

**Comment by ValentinH** [comment]
It's actually even more important than what I thought and I might want to rename the option to `retryOnConnAborted`: https://github.com/axios/axios/issues/1543

Indeed, axios uses `ECONNABORTED` for timeouts but also for actual connections being aborted (for other reasons). This is why we might want to retry in this case.

**Comment by mathiasose** [comment]
+1, I would also like to see this feature released.

In the meantime, this config should do the trick right?
```javascript
axiosRetry(axios, {
  retries: 3,
  shouldResetTimeout: true,
  retryCondition: (error) => isNetworkError(error) || isIdempotentRequestError(error) || error.code === 'ECONNABORTED',
});
```

Technically this config would also retry non-idempotent requests (e.g. `POST`), but I am only going to use this config with a specific `PUT` operation, so it should be safe right?

**Comment by ruscon** [comment]
Have the same issue, can we fix it ?

**Comment by eddyson1006** [comment]
> I understand that we can override the `retryCondition` with custom logic. However, I ended up copying the `isRetryableError`, `isIdempotentRequestError` and `isNetworkOrIdempotentRequestError` in my code just for removing the checks about `error.code !== 'ECONNABORTED'`. This doesn't feel right.
> 
> I also understand that the solution I propose isn't the best one but I couldn't find another way so far... :/

Putting this is interceptor will give timeout a retry.

**Pull request closed without merging**
