### PR TITLE
retryCondition should use promise value in return

### PR DESCRIPTION
**Pull request by PeterChen1997**
I think it's better to get the control back to user, it's more flexible

### CODE REVIEW

**Comment by YangChen00** [comment]
@mindhells plz have a look, thx

**Comment by mindhells** [comment]
you'd need to fix the tests
can you please give a little more context?

**Comment by PeterChen1997** [comment]
The condition is that i want use Promise<boolean> to control the retry result, instead of use throw error in it. It's not handy

**Comment by PeterChen1997** [comment]
The test i will have a look

**Comment by PeterChen1997** [comment]
solved, plz have a look again @mindhells

**Comment by mindhells** [comment]
I believe this relates to #190 

I missing 2 things to merge this PR:
- update the docs to note `retryCondition` should return a boolean
- don't change behavior for those using a retryCondition that just doesn't throw: this would mean return true unless `await shouldRetryOrPromise === false` 

WDYT?

**Comment by PeterChen1997** [comment]
Got it, i will have a look on it

**Comment by PeterChen1997** [comment]
@mindhells Done, have i got the point?

**Comment by mindhells** [comment]
> @mindhells Done, have i got the point?

Yes! I think so
thanks a lot
I'm going to merge a create a new release

**Review by mindhells — APPROVED** [review]

**Comment by mindhells** [comment]
v3.2.5 published!

**Pull request merged**
