### PR TITLE
Add option to maintain the timeout between retries

### PR DESCRIPTION
**Pull request by yns01**
Hey @rubennorte @jlopezxs 

I'd like to add an option to keep the timeout configured value between retries. As suggested in issue #24, I added a `shouldResetTimeout` option which defaults to `false` to keep the current behaviour.

Thanks!

### CODE REVIEW

**Comment by ValentinH** [comment]
I think this option could be merged with what's proposed in #39. Indeed, since we don't retry on timeouts at the moment, this option won't be useful unless the user re-implement the retry condition.

**Comment by yns01** [comment]
Hey @rubennorte @jlopezxs Do you think you'll have a moment to check this out?

**Comment by ValentinH** [comment]
Any chance to review this in a near future @rubennorte @jlopezxs ? 🙂

**Comment by jlopezxs** [comment]
Yes, sorry. And thanks for your contribution!

**Pull request merged**
